version: '3.8'

services:
  sara_backend:
    container_name: sara_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped






