version: "3.8"

services:
  tts_router:
    build:
      context: C:/Users/anjos/Desktop/SGPS/Sara/tts_openvoice
      dockerfile: Dockerfile
    container_name: tts_router_sara
    ports:
      - "5010:5000"
    restart: unless-stopped

  melotts:
    build:
      context: C:/Users/anjos/Desktop/SGPS/Sara/tts_melo
    container_name: melotts_sara
    ports:
      - "5011:5000"
    restart: unless-stopped

  parler:
    build:
      context: C:/Users/anjos/Desktop/SGPS/Sara/tts_parler
    container_name: parler_sara
    ports:
      - "5012:5000"
    restart: unless-stopped

  xtts:
    build:
      context: C:/Users/anjos/Desktop/SGPS/Sara/tts_xtts
    container_name: xtts_sara
    ports:
      - "5013:5000"
    restart: unless-stopped